#!/usr/bin/python

import RPi.GPIO as gpio

from time import sleep

# from display import Display
from vision_controller import Vision
from motion_controller import Motion
from motor_controller import Motor
from servo_controller import Servo
from camera import Camera

from sys import stdin, argv, exit
from signal import signal
from socket import *
from threading import Thread
from curses import *
from getch import getch

# setup
gpio.setmode(gpio.BCM)

"""
display = Display()
display.intro_anim()
"""

"""
center_vis = Vision(gpio, 17, 4)
display.center_vision(center_vis)
center_vis.start()

left_vis = Vision(gpio, 22, 27)
display.left_vision(left_vis)
left_vis.run()

right_vis = Vision(gpio, 9, 10)
display.right_vision(right_vis)
right_vis.run()
"""

# motion = Motion(gpio, (13, 6), (26, 19))
right_motor = Motor(gpio, (13, 6), 100)
left_motor = Motor(gpio, (26, 19), 100)

servo = Servo(gpio, 18)

"""
camera = Camera(fps=10)
camera.start()
"""

def cleanup(sig, frame):
    print "cleaning up!"
    gpio.cleanup()
    exit(0)

signal(2, cleanup)

def control_input(key):
    # TODO: arrow keys
    if key == ',' or key == 'w':
        print 'forward!'
        #motion.forward()
        left_motor.forward()
        right_motor.forward()
    elif key == 'a': 
        print 'turning left'
        #motion.rotate_left()
        left_motor.reverse()
        right_motor.forward()
    elif key == 'o' or key == 's':
        if left_motor.motion is None and right_motor.motion is None:
            print 'back it up'
            #motion.back()
            left_motor.reverse()
            right_motor.reverse()
        else:
            print 'stop'
            #motion.stop()
            left_motor.stop()
            right_motor.stop()

    elif key == 'e' or key == 'd':
        print 'turning right'
        # motion.rotate_right()
        left_motor.forward()
        right_motor.reverse()
    elif key == 'm':
        print 'motor control'

    elif key == KEY_UP:
        print 'uparrow'
    elif key == KEY_DOWN:
        print 'downarrow'
    elif key == KEY_LEFT:
        print 'leftarrow'
    elif key == KEY_RIGHT:
        print 'rightarrow'

    elif key == 'l':
        servo.rotate_down()
    elif key == 'L':
        servo.rotate_up()
    
    elif key == 'S':
        servo.set_rotation(0)
        sleep(1)
        servo.set_rotation(15)
        sleep(1)
        servo.set_rotation(30)
        sleep(1)



if len(argv) < 2 or argv[1] == '-l':
    print "You're the driver!"
    """
    screen = initscr()
    screen.keypad(True)
    noecho()
    cbreak()
    """

    c = 'true'
    while c:
        c = getch() #screen.getch()
        control_input(c)

    """
    echo()
    nocbreak()
    endwin()
    """


elif argv[1] == '-r':
    print "Remote driving enabled"
    sock = socket(AF_INET, SOCK_STREAM)
    sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)

    print sock
    sock.bind(('0.0.0.0', 6969))
    print 'bound'
    sock.listen(1)
    print 'started listening'

    try:
        while True:
            (rsock, addr) = sock.accept()
            print "Connected: ", addr

            try:
                while True:
                    c = rsock.recv(1)
                    if c:
                        control_input(c)
                    else:
                        print addr, 'disconnected'
                        break

            finally:
                rsock.close()
    finally:
        sock.close()

else:
    print "Bad Args:", argv[1:]

