#!/usr/bin/env python

import RPi.GPIO as gpio
from time import sleep
from vision_controller import VisionController
from motion_controller import MotionController

GPIO.setmode(gpio.BCM)

front_vision = VisionController(gpio,0,0)
left_vision = VisionController(gpio,0,0)
right_vision = VisionController(gpio,0,0)
motion = MotionController(gpio,0,0)

vision_controller.start()

too_close = 10
look_for_turn = 50

while True:
   if front_vision.updated or left_vision.updated or right_vision.updated:
 

gpio.cleanup()
