#!/usr/bin/env python

from time import sleep
from sys import stdout

class Motion:
    def __init__(self,gpio):

        self.right_wheel   = 0
        self.left_wheel    = 0
        self.time_per_inch = .01

        self.gpio = gpio
        self.gpio.setup(self.right_wheel,self.gpio.OUT)
        self.gpio.setup(self.left_wheel,self.gpio.OUT)

        self.stop()

    def turn_right(self):
        stdout.write("turning right...\n")
        self.rotate(-90)

    def turn_left(self):
        stdout.write("turning left...\n")
        self.rotate(90)

    def turn_around(self):
        stdout.write("turning around...\n")
        self.rotate(180)

    def rotate(self, deg=0):
        self.gpio.output(self.right_wheel, (deg < 0))
        self.gpio.output(self.left_wheel, (deg > 0))

        if abs(deg) > 0:
            sleep(.01 * abs(deg))
            stop()

    def go(self,inches=-1):
        stdout.write("Go!\n")
        self.gpio.output(self.right_wheel,True)
        self.gpio.output(self.left_wheel,True)

        if inches >= 0: 
            sleep(self.time_per_inch * inches)
            self.stop()

    def stop(self):
        stdout.write("stopping...\n")
        self.gpio.output(self.right_wheel,False)
        self.gpio.output(self.left_wheel,False)
