#!/usr/bin/env python

import RPi.GPIO as gpio
from time import sleep
from vision import Vision
from motion import Motion

GPIO.setmode(gpio.BCM)

vision_controller = Vision(gpio)
motion_controller = Motion(gpio)

vision_controller.start()

too_close = 10
look_for_turn = 50

while True:

    if vision_controller.updated:
        (left_dist, front_dist, right_dist) = vision_controller.refresh()

        if front_dist > too_close:
            motion_controller.go()
        
        #turn around if nowhere to go
        if front_dist < look_for_turn:

            if front_dist < too_close:
                motion_controller.stop()

            if right_dist > front_dist or left_dist > front_dist:
                if right_dist > left_dist:
                    motion_controller.turn_right()
                elif right_dist < left_dist:
                    motion_controller.turn_left()

            elif front_dist < too_close:
                motion_controller.turn_around()

stdout.write("All done!\n")
gpio.cleanup()
