#!./bin/python
from pygame import draw,display
from pygame.locals import *
from time import sleep

class Tracker:
    def __init__(self,motion_controller, rotation=0,location=(0,0)):
        self.rotation = rotation
        self.location = location
        self.graph = list()
        self.moving = False
        self.width = 640
        self.height = 480

        #draw.init()
        display.init()

    def rotate(self,deg):
        self.rotation += abs(deg)
    
    def xvisualize(self):
        self.window = display.set_mode((self.width,self.height))
        self.update()

    def ncvisualize(self):
        self.window = display.set_mode((self.width,self.height))
        self.update()

    def xupdate(self):
        for p in self.graph:
            draw.circle(self.window,(255,0,0),p,1)
        draw.lines(self.window, (0,0,255), False, self.graph)
        display.flip()
        display.update()

    def ncvisualize(self):
        
if __name__ == "__main__":
    t = Tracker()
    t.graph = ((100,100),(200,100),(200,200),(100,200))
    t.visualize()
    sleep(3)
        
